### PR TITLE
types: webhook event types

### PR DESCRIPTION
**Pull request by peterphanouvong**
# Explain your changes
- add webhook types
_Suppose there is a related issue with enough detail for a reviewer to understand your changes fully. In that case, you can omit an explanation and instead include either “Fixes #XX” or “Updates #XX” where “XX” is the issue number._

# Checklist

- [x] I have read the [“Pull requests” section](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md#pull-requests) in the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md).

🛟 _If you need help, consider asking for advice over in the [Kinde community](https://thekindecommunity.slack.com)._

## Summary by CodeRabbit

- **New Features**
	- Introduced new webhook events for enhanced integration capabilities, covering user actions, access requests, organization changes, permission modifications, role updates, and subscriber additions.

### CODE REVIEW

**Comment by DanielRivers** [comment]
coderabbitai review

**Comment by DanielRivers** [comment]
@coderabbitai review

**Comment by BrennenRocks** [comment]
I would suggest doing something more along these lines. This way will have a "base" type that the rest can pull from. That way if the base type changes we can add it in just 1 place and the rest will fall into place. I also prefer to use `type` instead of `interface` because of [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html).

```typescript
type WebhookEventDataMap = {
  'user.created': {
    user: {
      email: string | null;
      first_name: string;
      id: string;
      last_name: string;
      phone: string | null;
    };
  };
  'user.updated': {
    user: {
      email: string;
      first_name: string;
      id: string;
      is_password_reset_requested: boolean;
      is_suspended: boolean;
      last_name: string;
      organizations: Array<{
        roles: string[] | null;
        code: string;
        permissions: Array<{
          id: string;
          key: string;
        }> | null;
      }>;
      phone: string | null;
    };
  };
  'user.deleted': {
    user: {
      id: string;
    };
  };
  'user.authenticated': {
    user: {
      id: string;
    };
  };
  'user.authentication_failed': {
    user: {
      id: string;
    };
  };
  'access_request.created': {
    access_request: {
      email: string;
      first_name: string;
      last_name: string;
      user_id: string;
    };
  };
  'organization.created': {
    organization: {
      code: string;
      external_id: string | null;
      handle: string;
      name: string;
    };
  };
  'organization.updated': {
    organization: {
      code: string;
      external_id: string | null;
      handle: string;
      is_allow_registrations: boolean;
      name: string;
    };
  };
  'organization.deleted': {
    organization: {
      code: string;
    };
  };
  'permission.created': {
    permission: {
      description: string;
      id: string;
      key: string;
      name: string;
    };
  };
  'permission.updated': {
    permission: {
      description: string;
      id: string;
      key: string;
      name: string;
    };
  };
  'permission.deleted': {
    permission: {
      id: string;
    };
  };
  'role.created': {
    role: {
      description: string;
      id: string;
      is_default_role: boolean;
      key: string;
      name: string;
    };
  };
  'role.updated': {
    role: {
      description: string;
      id: string;
      is_default_role: boolean;
      key: string;
      name: string;
    };
  };
  'role.deleted': {
    role: {
      id: string;
    };
  };
  'subscriber.created': {
    subscriber: {
      email: string;
      first_name: string;
      id: string;
      last_name: string;
      user_id: string;
    };
  };
}

type WebhookEvent<TType extends keyof WebhookEventDataMap> = {
  data: WebhookEventDataMap[TType];
  event_id: string;
  source: WebhookSource;
  timestamp: string;
  type: TType;
}

export type UserCreatedWebhookEvent = WebhookEvent<'user.created'>;
export type UserUpdatedWebhookEvent = WebhookEvent<'user.updated'>;
...
export type RoleDeletedWebhookEvent = WebhookEvent<'role.deleted'>;
export type SubscriberCreatedWebhookEvent = WebhookEvent<'subscriber.created'>;
```

**Comment by DanielRivers** [comment]
Hi, @BrennenRocks 

Agree, the main reason this has not been merged as we have another solution in the works to handle webhooks. I hope to be able to share soon!

**Comment by DanielRivers** [comment]
Hi @BrennenRocks , 

We have released the [@kinde-oss/webhooks](https://github.com/kinde-oss/webhook) package which has types and handing.

**Pull request closed without merging**
